package core

import "github.com/pkg/errors"

var (
	MathError                             = errors.New("Math error")
	AccountNotFound                       = errors.New("Account not found")
	BankAssetNotMatch                     = errors.New("Bank asset not match")
	InvalidAction                         = errors.New("Invalid action")
	TooManyAccounts                       = errors.New("too many accounts")
	BankNotFound                          = errors.New("Bank not found")
	GroupNotFound                         = errors.New("Group not found")
	LendingAccountBalanceNotFound         = errors.New("Lending account balance not found")
	BankAssetCapacityExceeded             = errors.New("Bank asset capacity exceeded")
	InvalidTransfer                       = errors.New("Invalid transfer")
	MissingPythOrBankAccount              = errors.New("Missing Pyth or Bank account")
	MissingPythAccount                    = errors.New("Missing Pyth account")
	InvalidOracleAccount                  = errors.New("Invalid Oracle account")
	MissingBankAccount                    = errors.New("Missing Bank account")
	InvalidBankAccount                    = errors.New("Invalid Bank account")
	RiskEngineInitRejected                = errors.New("Risk engine init rejected")
	BankAlreadyExists                     = errors.New("Bank already exists")
	IllegalLiquidation                    = errors.New("Illegal liquidation")
	AccountNotBankrupt                    = errors.New("Account is not bankrupt")
	BalanceNotBadDebt                     = errors.New("Account balance is not bad debt")
	InvalidConfig                         = errors.New("Invalid group config")
	StaleOracle                           = errors.New("Stale oracle data")
	BankPaused                            = errors.New("Bank paused")
	BankReduceOnly                        = errors.New("Bank is ReduceOnly mode")
	BankAccountNotFound                   = errors.New("Bank account not found")
	OperationDepositOnly                  = errors.New("Operation is deposit-only")
	OperationWithdrawOnly                 = errors.New("Operation is withdraw-only")
	OperationBorrowOnly                   = errors.New("Operation is borrow-only")
	OperationRepayOnly                    = errors.New("Operation is repay-only")
	NoAssetFound                          = errors.New("No asset found")
	NoLiabilityFound                      = errors.New("No liability found")
	InvalidOracleSetup                    = errors.New("Invalid oracle setup")
	IllegalUtilizationRatio               = errors.New("Invalid bank utilization ratio")
	BankLiabilityCapacityExceeded         = errors.New("Bank borrow cap exceeded")
	InvalidPrice                          = errors.New("Invalid Price")
	IsolatedAccountIllegalState           = errors.New("Account is not bankrupt")
	EmissionsAlreadySetup                 = errors.New("Emissions already setup")
	OracleNotSetup                        = errors.New("Oracle is not set")
	InvalidSwitchboardDecimalConversion   = errors.New("Invalid Switchboard decimal conversion")
	CannotCloseOutstandingEmissions       = errors.New("Cannot close outstanding emissions")
	EmissionsUpdateError                  = errors.New("Update emissions error")
	AccountDisabled                       = errors.New("Account disabled")
	AccountTempActiveBalanceLimitExceeded = errors.New("Account can't temporarily open 3 balances, please close a balance first")
	AccountInFlashloan                    = errors.New("Illegal action during flashloan")
	IllegalFlashloan                      = errors.New("Illegal flashloan")
	IllegalFlag                           = errors.New("Illegal flag")
	IllegalBalanceState                   = errors.New("Illegal balance state")
	IllegalAccountAuthorityTransfer       = errors.New("Illegal account authority transfer")
	Unauthorized                          = errors.New("Unauthorized")
	IllegalAction                         = errors.New("Illegal action")
	T22MintRequired                       = errors.New("Token22 Banks require mint account as first remaining account")
)

var (
	ErrInternalServerError = errors.New("internal server error")

	ErrReadMixinSafeSnapshotFailed = errors.New("read mixin safe snapshot failed")
	ErrGetSnapshotCountFailed      = errors.New("get snapshot count failed")
	ErrGetLastestSnapshotFailed    = errors.New("get lastest snapshot failed")
	ErrGetSnapshotByIdFailed       = errors.New("get snapshot by id failed")

	ErrSnapshotNotFound               = errors.New("snapshot not found")
	ErrNewAccountFailed               = errors.New("new account failed")
	ErrDecodeMemoFailed               = errors.New("decode memo failed")
	ErrHandleRepayFailed              = errors.New("handle repay failed")
	ErrHandleWithdrawFailed           = errors.New("handle withdraw failed")
	ErrHandleBorrowFailed             = errors.New("handle borrow failed")
	ErrHandleWithdrawEmissionsFailed  = errors.New("handle withdraw emissions failed")
	ErrHandleAccrueBankInterestFailed = errors.New("handle accrue bank interest failed")
	ErrHandleWithdrawFeesFailed       = errors.New("handle withdraw fees failed")
	ErrHandleWithdrawInsuranceFailed  = errors.New("handle withdraw insurance failed")
	ErrHandleLoopFailed               = errors.New("handle loop failed")
	ErrHandleDepositFailed            = errors.New("handle deposit failed")
	ErrBankLiquidityDeficit           = errors.New("bank liquidity deficit")
	ErrInvalidBankConfig              = errors.New("invalid bank config")
	ErrOracleMaxAgeTooLong            = errors.New("oracle max age is too long")
	ErrUnknownOracleSetup             = errors.New("unknown oracle setup")
	ErrAccountNotUnhealthy            = errors.New("account not unhealthy")
	ErrTransferAmount                 = errors.New("transfer amount is not positive")
	ErrInsufficientBalance            = errors.New("insufficient balance")

	ErrBankAccountNil = errors.New("bank account is nil")
)

var (
	ErrNegativeInterestRate = errors.New("negative interest rate")

	ErrOptimalUr             = errors.New("optimal utilization rate must be between 0 and 1")
	ErrPlateauIr             = errors.New("plateau interest rate must be positive")
	ErrMaxIr                 = errors.New("max interest rate must be positive")
	ErrPlateauGreaterThanMax = errors.New("plateau interest rate must be less than max interest rate")
)

var (
	ErrPriceCacheDirty = errors.New("price cache dirty")
)

var (
	ErrNotEnoughUtxos = errors.New("not enough utxos")
	ErrInvalidUtxos   = errors.New("invalid utxos")
)
